# Algorithm for Cart-Pole

Import necessary libries

In [46]:
import gym
import numpy as np
import time

Create Environment

In [47]:
env=gym.make("CartPole-v1",render_mode="human")
env.reset()

(array([ 0.04878455,  0.03133567, -0.02171667, -0.00937178], dtype=float32),
 {})

Render the Environment

In [48]:
env.render()

Close the environment

In [49]:
# env.close()

push cart in one direction

In [50]:
env.step(0)

(array([ 0.04941126, -0.16346821, -0.0219041 ,  0.27638096], dtype=float32),
 1.0,
 False,
 False,
 {})

observation space limit

In [51]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

Upper Limit

In [52]:
env.observation_space.high

array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32)

Lower Limit

In [53]:
env.observation_space.low

array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32)

Action Space

In [54]:
env.action_space

Discrete(2)

All the Specs

In [55]:
env.spec

EnvSpec(id='CartPole-v1', entry_point='gym.envs.classic_control.cartpole:CartPoleEnv', reward_threshold=475.0, nondeterministic=False, max_episode_steps=500, order_enforce=True, autoreset=False, disable_env_checker=False, apply_api_compatibility=False, kwargs={'render_mode': 'human'}, namespace=None, name='CartPole', version=1)

Maximum Number of steps per episode

In [56]:
env.spec.max_episode_steps

500

reward threshold per episode

In [57]:
env.spec.reward_threshold

475.0

In [58]:
# simulate the environment
episodeNumber=5
timeSteps=100
 

for episodeIndex in range(episodeNumber):
    initial_state=env.reset()
    print(episodeIndex)
    env.render()
    appendedObservations=[]
    for timeIndex in range(timeSteps):
        print(timeIndex)
        random_action=env.action_space.sample()
        observation, reward, terminated, truncated, info =env.step(random_action)
        appendedObservations.append(observation)
        time.sleep(0.1)
        if (terminated):
            time.sleep(1)
            break


0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
1
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
2
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
3
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
4
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [59]:
env.close()